"$schema" = "../node_modules/wrangler/config-schema.json"

name = "cert-vait-au"
workers_dev = false
preview_urls = false
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "cert.vait.au"
custom_domain = true

[assets]
directory = "dist"

[observability]
enabled = true
head_sampling_rate = 1
